### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by ChrisKam** [fabrik42/responsive_mockups#2]
Hi Christian,

thank you for this neat script, I'm planning to use it to create all mockups for my new website but I've ran into an issue: When there is no background-color on certain elements, phantomjs correctly renders them with transparency. This causes a problem however with responsive_mockups as there is stuff in the template files already. I was able to fix this by having a white background inside each device in these files (which I think is a safe assumption to make).

I'll submit a pull request on this when I get to it...

**Comment by fabrik42** [comment]
ah - yes, you're right. I always kept the background of the devices in the psd, because I wanted to keep the fake browser toolbar.

Do you plan to keep the browser toolbar and just get rid of the other stuff within the device screens?

**Comment by ChrisKam** [comment]
Just the other stuff, yes - it can also be slightly misleading when there is no output at all. At first I was like "what is this page?" I'll submit the request asap

**Comment by fabrik42** [comment]
Yes, you're totally right. Thanks for your help!

**Comment by fabrik42** [comment]
Hi! Any updates on this?

**Comment by ChrisKam** [comment]
Woops, apologies for letting this one drop. I'm afraid I have stopped using responsive mockups altogether, I just couldn't get the fonts to render as crisp or in certain cases, with the correct weights. I might pick this project back up once Phantom JS solves these problems for good - this issue however can be closed :-(

**Comment by fabrik42** [comment]
Alright :)
