### ISSUE TITLE
how I do put this code?

### ISSUE THREAD

**Issue by guangrei** [fabrik42/responsive_mockups#7]
hi I have googling how to handle transparent background on phantomjs and found this one but still don't know where I put this code on responsive mockups

> page.evaluate(function(){
> document.body.bgColor='white';
> });

**Comment by fabrik42** [comment]
Hi!
Is the problem related to the screenshot images or the generated mockup image?

**Comment by guangrei** [comment]
thank for reply, the problem is related to the screenshot images, it come with transparency background on some website

**Comment by fabrik42** [comment]
This is where the screenshots are rendered: https://github.com/fabrik42/responsive_mockups/blob/master/index.js#L18

So I think you need to put your code right above the `page.render` call.
